/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { EnveloopApi } from "@fern-api/enveloop";

export interface Template {
  /** An array of the user defined variables found in the template */
  templateVariables: EnveloopApi.Variable[];
  /** A preview of the body of the message with `{{ variables }}` intact like you would see at in the Enveloop editor. */
  body: string;
}
