/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { EnveloopApi } from "@fern-api/enveloop";
import * as core from "../../../core";

export const Request: core.schemas.Schema<serializers.messages.send.Request.Raw, EnveloopApi.SendMessageRequest> =
  core.schemas.lazyObject(async () => (await import("../..")).SendMessageRequest);

export declare namespace Request {
  type Raw = serializers.SendMessageRequest.Raw;
}

export const Response: core.schemas.Schema<serializers.messages.send.Response.Raw, EnveloopApi.SendMessageResponse> =
  core.schemas.lazyObject(async () => (await import("../..")).SendMessageResponse);

export declare namespace Response {
  type Raw = serializers.SendMessageResponse.Raw;
}
