/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface SendMessageRequest {
  /** The `template` field is required and should be the template slug you wish to send. */
  template: string;
  /** The `to` field is required to send a message. It should be a single recipient. */
  to: string;
  /**
   * The `from` field is optional on the API call as long as it is set on either the *Template* or the *Provider*.
   * The order of precedence for the from field on a message is:
   *   1. from attribute in the API call
   *   2. If not set in API call it will look in *Template* defaults
   *   3. If not set in *Template* it will look in *Provider* defaults
   *   4. If not set in 1-3 it will return an error and fail to send *Message*
   *
   */
  from?: string;
  /** The `subject` field is optional on the API call as long as it is set in the *Template* defaults. */
  subject?: string;
  /**
   * The `templateVariables` field accepts a hash/object of variables and text to replace in the template.
   * For example if you have the text `Hello {{user}}` in your template and pass `{ user: "Bob" }` as `templateVariables` then the template will render `Hello Bob`
   *
   */
  templateVariables: Record<string, string>;
}
