/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { EnveloopApi } from "@fern-api/enveloop";
import * as core from "../../../core";

export const SendMessageRequest: core.schemas.ObjectSchema<
  serializers.SendMessageRequest.Raw,
  EnveloopApi.SendMessageRequest
> = core.schemas.object({
  template: core.schemas.string(),
  to: core.schemas.string(),
  from: core.schemas.string().optional(),
  subject: core.schemas.string().optional(),
  templateVariables: core.schemas.record(core.schemas.string(), core.schemas.string()),
});

export declare namespace SendMessageRequest {
  interface Raw {
    template: string;
    to: string;
    from?: string | null;
    subject?: string | null;
    templateVariables: Record<string, string>;
  }
}
