/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { EnveloopApi } from "@fern-api/enveloop";
import * as core from "../../../core";

export const SendMessageResponse: core.schemas.ObjectSchema<
  serializers.SendMessageResponse.Raw,
  EnveloopApi.SendMessageResponse
> = core.schemas.object({
  to: core.schemas.string(),
  from: core.schemas.string(),
  body: core.schemas.string(),
});

export declare namespace SendMessageResponse {
  interface Raw {
    to: string;
    from: string;
    body: string;
  }
}
