/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments";
import * as core from "./core";
import { Client as MessagesClient } from "./resources/messages/client/Client";
import { Client as TemplatesClient } from "./resources/templates/client/Client";

export declare namespace EnveloopApiClient {
  interface Options {
    environment?: environments.Environment | string;
    token?: core.Supplier<core.BearerToken>;
  }
}

export class EnveloopApiClient {
  constructor(private readonly options: EnveloopApiClient.Options) {}

  #messages: MessagesClient | undefined;

  public get messages(): MessagesClient {
    return (this.#messages ??= new MessagesClient(this.options));
  }

  #templates: TemplatesClient | undefined;

  public get templates(): TemplatesClient {
    return (this.#templates ??= new TemplatesClient(this.options));
  }
}
