/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const Environment = {
  /**
   * Production tokens begin with `live_` and will send actual messages with the configured provider.
   */
  Production: "https://api.enveloop.com",
  /**
   * Sandbox token begin with `test_` and only mock the sending action.  Therefore, calls made from your app, using your sandbox token, do not connect to the provider on the project.
   *
   */
  Sandbox: "https://sandbox.enveloop.com",
} as const;

export type Environment = typeof Environment.Production | typeof Environment.Sandbox;
